import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { collection, getDocs } from 'firebase/firestore';
import AdminRouteDock from '../components/AdminRouteDock';
import { db } from '../firebase/config';
import './SiteSurveyReports.css';

const typeName = { floor: 'พื้น', wall: 'ผนัง', roof: 'หลังคา', plumbing: 'งานระบบน้ำ', electrical: 'งานระบบไฟ', other: 'อื่นๆ' };
const stamp = value => value?.toDate ? value.toDate().toLocaleDateString('th-TH') : value || '—';

export default function SiteSurveyReports() {
  const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(true);
  const load = async () => { setBusy(true); try { const snap = await getDocs(collection(db, 'siteSurveys')); setRows(snap.docs.map(item => ({ id:item.id, ...item.data() })).sort((a,b) => String(b.surveyDate || '').localeCompare(String(a.surveyDate || '')))); } finally { setBusy(false); } };
  useEffect(() => { Promise.resolve().then(load); }, []);
  const filtered = useMemo(() => rows.filter(item => `${item.customer} ${item.projectName} ${item.address}`.toLowerCase().includes(query.toLowerCase())), [rows,query]);
  return <><AdminRouteDock activePath="/admin/site-survey-reports"/><main className="survey-reports"><header><div><Link to="/admin">← ระบบจัดการ</Link><p>ขั้นที่ 2 จาก 6 · รายงานสำรวจ</p><h1>รายงานสำรวจหน้างาน</h1><span>ดูข้อมูลวัดพื้นที่ รูปประกอบ และพิกัดก่อนสร้างใบเสนอราคา</span></div><Link className="survey-new" to="/admin/site-survey">＋ สำรวจใหม่</Link></header><input className="survey-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="ค้นหาชื่อลูกค้า โครงการ หรือสถานที่"/>{busy ? <p>กำลังโหลดรายงาน…</p> : <section className="survey-report-list">{filtered.length ? filtered.map(item=><button key={item.id} onClick={()=>setSelected(item)}><b>{item.projectName}</b><span>{item.customer} · {stamp(item.surveyDate)}</span><small>{item.totalArea?.toFixed?.(2) || '0.00'} ตร.ม. · {(item.photos || []).length} รูป</small></button>) : <p className="survey-empty">ยังไม่มีผลสำรวจ เริ่มบันทึกจากปุ่ม “สำรวจใหม่”</p>}</section>}</main>{selected&&<div className="survey-report-modal" role="dialog" aria-modal="true"><button className="survey-report-backdrop" onClick={()=>setSelected(null)} aria-label="ปิด"/><section><header><div><small>{selected.customer} · {stamp(selected.surveyDate)}</small><h2>{selected.projectName}</h2><p>{selected.address || 'ไม่ระบุสถานที่'}</p></div><button onClick={()=>setSelected(null)}>×</button></header>{selected.location&&<a className="survey-map" href={`https://www.google.com/maps?q=${selected.location.latitude},${selected.location.longitude}`} target="_blank" rel="noreferrer">⌖ เปิดพิกัดในแผนที่</a>}<div className="survey-measurements">{(selected.measurements || []).map((row,index)=><article key={row.id || index}><b>{typeName[row.pointType] || 'จุดวัด'} · {row.point || `จุดงาน ${index + 1}`}</b><span>{row.width || 0} × {row.length || 0} × {row.qty || 1} = <strong>{Number(row.area || 0).toFixed(2)} ตร.ม.</strong></span>{row.note&&<p>{row.note}</p>}<div className="survey-report-photos">{(selected.photos || []).filter(photo=>photo.measurementId === row.id).map(photo=><a key={photo.id} href={photo.driveUrl} target="_blank" rel="noreferrer">📷 {photo.name}</a>)}</div></article>)}</div><footer><b>พื้นที่รวม {Number(selected.totalArea || 0).toFixed(2)} ตร.ม.</b>{selected.note&&<p>{selected.note}</p>}</footer></section></div>}</>;
}
