import { useState } from 'react';
import { Link } from 'react-router-dom';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import AdminRouteDock from '../components/AdminRouteDock';
import { db } from '../firebase/config';
import './SiteSurvey.css';

const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' });
const empty = () => ({ id: crypto.randomUUID(), point: '', width: '', length: '', height: '', qty: '1', note: '' });
const number = value => Math.max(0, Number(value) || 0);

export default function SiteSurvey() {
  const [projectName, setProjectName] = useState(''); const [customer, setCustomer] = useState(''); const [date, setDate] = useState(today);
  const [contact, setContact] = useState(''); const [address, setAddress] = useState(''); const [note, setNote] = useState(''); const [rows, setRows] = useState([empty()]);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const area = row => number(row.width) * number(row.length) * number(row.qty);
  const total = rows.reduce((sum, row) => sum + area(row), 0);
  const change = (id, field, value) => setRows(current => current.map(row => row.id === id ? { ...row, [field]: value } : row));
  const save = async event => { event.preventDefault(); if (!projectName.trim() || !customer.trim()) return setMessage('กรอกชื่อลูกค้าและชื่อโครงการก่อน'); try { setBusy(true); setMessage('กำลังบันทึกผลสำรวจ…'); await addDoc(collection(db, 'siteSurveys'), { quoteId:'', quoteNumber:'', projectName:projectName.trim(), customer:customer.trim(), surveyDate: date, contact:contact.trim(), address:address.trim(), note:note.trim(), measurements:rows.map(row => ({ ...row, area:area(row) })), totalArea:total, status:'surveyed', createdAt:serverTimestamp(), updatedAt:serverTimestamp() }); setMessage(`บันทึกแล้ว · พื้นที่รวม ${total.toFixed(2)} ตร.ม. พร้อมสร้างใบเสนอราคา`); setRows([empty()]); setNote(''); } catch { setMessage('บันทึกไม่สำเร็จ ลองใหม่อีกครั้ง'); } finally { setBusy(false); } };
  return <><AdminRouteDock activePath="/admin/site-survey"/><main className="site-survey"><Link to="/admin">← ระบบจัดการ</Link><p>ขั้นที่ 2 จาก 6 · สำรวจหน้างาน</p><h1>ข้อมูลลูกค้าและวัดพื้นที่</h1><span>บันทึกก่อน แล้วจึงนำไปสร้างใบเสนอราคา</span><form onSubmit={save}><div className="survey-grid"><label>ชื่อลูกค้า<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="ชื่อผู้ว่าจ้าง"/></label><label>ชื่อโครงการ<input value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="เช่น ต่อเติมครัวบ้านคุณสมชาย"/></label></div><div className="survey-grid"><label>วันที่<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>ผู้ติดต่อ<input value={contact} onChange={e=>setContact(e.target.value)} placeholder="ชื่อ / โทรศัพท์"/></label></div><label>สถานที่ / จุดนัดหมาย<textarea value={address} onChange={e=>setAddress(e.target.value)} placeholder="บ้านเลขที่, ซอย, จุดสังเกต"/></label><section><header><b>จุดที่ต้องวัด</b><strong>รวม {total.toFixed(2)} ตร.ม.</strong></header>{rows.map((row,index)=><article key={row.id}><input value={row.point} onChange={e=>change(row.id,'point',e.target.value)} placeholder={`จุดงาน ${index+1} เช่น พื้นครัว`}/><div className="survey-measure"><input inputMode="decimal" value={row.width} onChange={e=>change(row.id,'width',e.target.value)} placeholder="กว้าง ม."/><span>×</span><input inputMode="decimal" value={row.length} onChange={e=>change(row.id,'length',e.target.value)} placeholder="ยาว ม."/><input inputMode="decimal" value={row.qty} onChange={e=>change(row.id,'qty',e.target.value)} placeholder="จำนวน"/></div><small>{area(row).toFixed(2)} ตร.ม.</small><textarea value={row.note} onChange={e=>change(row.id,'note',e.target.value)} placeholder="สภาพงาน / วัสดุ / ข้อสังเกต"/></article>)}<button type="button" className="survey-add" onClick={()=>setRows(current=>[...current,empty()])}>＋ เพิ่มจุดวัด</button></section><label>หมายเหตุสำคัญ<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="สิ่งที่ต้องประเมินเพิ่ม หรือแจ้งลูกค้า"/></label><button className="survey-save" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกผลสำรวจ'}</button>{message&&<p role="status">{message}</p>}</form></main></>;
}
