import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import AdminRouteDock from '../components/AdminRouteDock';
import { archiveSiteUpdate, createSiteUpdate, listSiteUpdates, markSiteUpdateFailed, requestDriveSync, uploadSiteUpdatePhotos, validateSitePhotos } from '../firebase/siteUpdates';
import { getAllProjects } from '../firebase/api';
import './SiteUpdates.css';

const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' });
const formatDate = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString('th-TH', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
const statusLabel = { draft: 'ร่าง', uploading: 'กำลังส่ง', saved: 'บันทึกแล้ว', failed: 'ส่งไม่สำเร็จ', archived: 'เก็บเข้าคลัง' };

export default function SiteUpdates() {
  const [projects, setProjects] = useState([]), [projectId, setProjectId] = useState(''), [date, setDate] = useState(today), [note, setNote] = useState(''), [files, setFiles] = useState([]), [updates, setUpdates] = useState([]), [busy, setBusy] = useState(false), [progress, setProgress] = useState(''), [error, setError] = useState('');
  const project = useMemo(() => projects.find(item => String(item.id) === projectId), [projects, projectId]);
  const reload = async () => { const data = await listSiteUpdates(); setUpdates(data.filter(item => item.status !== 'archived')); };
  useEffect(() => { getAllProjects().then(data => { setProjects(data); setProjectId(data[0] ? String(data[0].id) : ''); }).catch(() => setError('โหลดโครงการไม่สำเร็จ')); listSiteUpdates().then(data => setUpdates(data.filter(item => item.status !== 'archived'))).catch(() => setError('โหลดรายการอัปเดตไม่สำเร็จ')); }, []);
  const chooseFiles = event => { try { setFiles(validateSitePhotos(event.target.files)); setError(''); } catch (err) { setFiles([]); setError(err.message); event.target.value = ''; } };
  const save = async event => { event.preventDefault(); if (!project) { setError('เลือกโครงการก่อน'); return; } let update; try { setBusy(true); setError(''); setProgress('กำลังสร้างรายการ…'); update = await createSiteUpdate({ project, updateDate: date, note }); const photos = await uploadSiteUpdatePhotos(update.id, files, (done, total) => setProgress(`กำลังเตรียมรูป ${done}/${total}`)); setProgress(`เตรียมรูป ${photos.length} รูปแล้ว กำลังส่งเข้า Drive…`); const result = await requestDriveSync(update.id, update.operationId, photos); setProgress('บันทึกและส่งเข้า Drive แล้ว'); setFiles([]); setNote(''); await reload(); if (result.driveUrl) window.open(result.driveUrl, '_blank', 'noopener'); } catch (err) { if (update) await markSiteUpdateFailed(update.id, err.message); setError(err.message); setProgress(''); } finally { setBusy(false); } };
  const retry = async item => { try { setBusy(true); setError(''); await requestDriveSync(item.id, item.operationId, item.photos || []); await reload(); } catch (err) { await markSiteUpdateFailed(item.id, err.message); setError(err.message); await reload(); } finally { setBusy(false); } };
  return <><AdminRouteDock activePath="/admin/site-updates" /><main className="site-updates"><header><div><Link to="/admin">← ระบบจัดการ</Link><p>อัปเดตรูปหน้างาน</p><h1>บันทึกภาพตามวันที่</h1><span>รูปต้นฉบับส่งเข้า Google Drive ภาพตัวอย่างอยู่ในระบบ 15 วัน</span></div><button onClick={() => reload()} disabled={busy}>รีเฟรช</button></header><section className="site-update-compose"><form onSubmit={save}><div className="site-update-heading"><b>อัปเดตใหม่</b><small>ใช้งานจากมือถือได้ทันที</small></div><label>โครงการ<select value={projectId} onChange={event => setProjectId(event.target.value)} disabled={busy}>{projects.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>วันที่<input type="date" value={date} onChange={event => setDate(event.target.value)} disabled={busy}/></label><label>ข้อความสำคัญ <small>เว้นว่างได้</small><textarea value={note} onChange={event => setNote(event.target.value)} maxLength="2000" placeholder="เช่น เทปูนพื้นชั้น 1 เสร็จแล้ว / รอส่งกระเบื้อง" disabled={busy}/></label><label className="site-photo-picker"><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple capture="environment" onChange={chooseFiles} disabled={busy}/><b>＋ ถ่ายรูป / เลือกรูป</b><span>{files.length ? `เลือกแล้ว ${files.length} รูป` : 'JPG, PNG, WebP, HEIC · รูปละไม่เกิน 12 MB'}</span></label>{files.length > 0 && <div className="site-file-list">{files.map(file => <span key={`${file.name}-${file.lastModified}`}>{file.name}<small>{Math.ceil(file.size / 1024 / 1024 * 10) / 10} MB</small></span>)}</div>}<button className="site-save" disabled={busy || !files.length}>{busy ? (progress || 'กำลังบันทึก…') : 'บันทึกและส่งรูปเข้า Drive'}</button>{progress && <p className="site-progress" role="status">{progress}</p>}{error && <p className="site-error" role="alert">{error}</p>}</form></section><section className="site-update-list"><div><p>รายการล่าสุด</p><h2>อัปเดตรูปหน้างาน</h2></div>{updates.length === 0 && <p className="site-empty">ยังไม่มีอัปเดต เริ่มได้จากฟอร์มด้านบน</p>}{updates.map(item => <article key={item.id}><div className="site-update-meta"><b>{item.projectName}</b><span>{formatDate(item.updateDate)} · {statusLabel[item.status] || item.status}</span>{item.note && <p>{item.note}</p>}</div><div className="site-thumbs">{(item.photos || []).slice(0, 4).map(photo => <img key={photo.id} src={photo.thumbnailUrl} alt={photo.caption || photo.name} />)}</div><footer>{item.driveUrl && <a href={item.driveUrl} target="_blank" rel="noreferrer">เปิด Drive ↗</a>}{item.status === 'failed' && <button onClick={() => retry(item)} disabled={busy}>ส่งซ้ำ</button>}<button onClick={() => archiveSiteUpdate(item.id).then(reload)} disabled={busy}>เก็บ</button></footer></article>)}</section></main></>;
}
