import { money } from '../lib/quotation';

export default function ReceiptA4Form({ receipt, calculation, locked, actions, edit, itemEdit, addItem, removeItem }) {
  return <article className="quote-paper quote-a4-form receipt-form">
    <div className="quote-form-actions">{actions}</div>
    <fieldset className="quote-a4-fields" disabled={locked}>
      <header className="quote-heading quote-form-heading"><div className="quote-brand-fields"><label>ผู้รับเงิน<input value={receipt.seller} onChange={e => edit('seller', e.target.value)} /></label><label>เบอร์ผู้รับเงิน<input value={receipt.sellerPhone} onChange={e => edit('sellerPhone', e.target.value)} /></label></div><div><h1>ใบเสร็จรับเงิน</h1><label>เลขใบเสร็จ<input value={receipt.number} maxLength="50" placeholder="RC-001" onChange={e => edit('number', e.target.value)} /></label><label>วันที่<input type="date" value={receipt.date} onChange={e => edit('date', e.target.value)} /></label></div></header>
      <section className="quote-customer quote-form-customer"><label>ได้รับเงินจาก<input value={receipt.payer} onChange={e => edit('payer', e.target.value)} /></label><label>เบอร์โทร<input value={receipt.phone} onChange={e => edit('phone', e.target.value)} /></label><label>โครงการ<input value={receipt.project} onChange={e => edit('project', e.target.value)} /></label><label>อ้างอิงใบเสนอราคา<input value={receipt.quoteNumber} onChange={e => edit('quoteNumber', e.target.value)} /></label></section>
      <table className="quote-table receipt-edit-table"><thead><tr><th>รายการรับเงิน</th><th>จำนวนเงิน (บาท)</th><th className="quote-edit-only">จัดการ</th></tr></thead><tbody>{receipt.items.map((item, index) => <tr key={item.id}><td><textarea rows="2" aria-label={`รายละเอียดรับเงิน ${index + 1}`} value={item.description} onChange={e => itemEdit(index, 'description', e.target.value)} /></td><td><input inputMode="decimal" aria-label={`จำนวนเงิน ${index + 1}`} value={item.amount} onChange={e => itemEdit(index, 'amount', e.target.value)} /></td><td className="quote-edit-only"><button type="button" className="quote-icon-button quote-danger" aria-label={`ลบรายการรับเงิน ${index + 1}`} onClick={() => removeItem(index)}>×</button></td></tr>)}</tbody></table>
      <button type="button" className="quote-edit-only quote-add-section" onClick={addItem}>+ เพิ่มรายการรับเงิน</button>
      <div className="quote-totals quote-form-totals"><p className="quote-grand">รวมเงินที่ได้รับ <b>{calculation.totals ? `${money(calculation.totals.total)} บาท` : 'คำนวณไม่สำเร็จ'}</b></p></div>
      {calculation.error ? <p className="quote-calc-error" role="alert">{calculation.error}</p> : <p className="quote-calc-ready quote-edit-only">✓ คำนวณยอดอัตโนมัติแล้ว พร้อมบันทึก</p>}
      <section className="quote-form-customer receipt-details"><label>ชำระโดย<select value={receipt.paymentMethod} onChange={e => edit('paymentMethod', e.target.value)}><option>โอนเงิน</option><option>เงินสด</option><option>เช็ค</option><option>บัตร</option><option>อื่น ๆ</option></select></label><label>เลขอ้างอิง<input value={receipt.paymentReference} onChange={e => edit('paymentReference', e.target.value)} /></label><label className="quote-project-field">หมายเหตุ<textarea rows="3" value={receipt.note} onChange={e => edit('note', e.target.value)} /></label></section>
      <div className="quote-signatures"><div>ผู้ชำระเงิน<br/><span>ลงชื่อ ____________________</span><p>วันที่ ____________________</p></div><div>ผู้รับเงิน<br/><span>ลงชื่อ ____________________</span><p>วันที่ ____________________</p></div></div>
    </fieldset>
  </article>;
}
